In [1]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np


# Load cleaned dataset
df = pd.read_csv(
    "../../../data/processed/diabetes_cleaned.csv"
)


print("=" * 70)
print("PROCESSED DATASET")
print("=" * 70)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")


display(df.head())

======================================================================
PROCESSED DATASET
======================================================================
Rows    : 229474
Columns : 22

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [2]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================


target_column = "Diabetes_binary"


X = df.drop(
    target_column,
    axis=1
)


y = df[target_column]



print("=" * 70)
print("FEATURE MATRIX (X)")
print("=" * 70)

print(f"Rows    : {X.shape[0]}")
print(f"Columns : {X.shape[1]}")


print("\n" + "=" * 70)
print("TARGET VARIABLE (y)")
print("=" * 70)

print(f"Rows : {y.shape[0]}")

display(y.head())

======================================================================
FEATURE MATRIX (X)
======================================================================
Rows    : 229474
Columns : 21

======================================================================
TARGET VARIABLE (y)
======================================================================
Rows : 229474

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Diabetes_binary, dtype: float64

In [3]:
# =============================================================================
# STEP 3: VERIFY TARGET DISTRIBUTION
# =============================================================================


print("=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)


display(
    y.value_counts()
)


print("\nClass Percentage")


display(
    (y.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    194377
1.0     35097
Name: count, dtype: int64

Class Percentage

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [4]:
# =============================================================================
# STEP 4: FEATURE TYPE CHECK
# =============================================================================


print("=" * 70)
print("FEATURE DATA TYPES")
print("=" * 70)


display(
    X.dtypes.to_frame(
        name="Data Type"
    )
)

======================================================================
FEATURE DATA TYPES
======================================================================

                     Data Type
HighBP                 float64
HighChol               float64
CholCheck              float64
BMI                    float64
Smoker                 float64
Stroke                 float64
HeartDiseaseorAttack   float64
PhysActivity           float64
Fruits                 float64
Veggies                float64
HvyAlcoholConsump      float64
AnyHealthcare          float64
NoDocbcCost            float64
GenHlth                float64
MentHlth               float64
PhysHlth               float64
DiffWalk               float64
Sex                    float64
Age                    float64
Education              float64
Income                 float64

In [5]:
# =============================================================================
# STEP 3: TRAIN-TEST SPLIT
# =============================================================================


from sklearn.model_selection import train_test_split


print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


print("Training Data")
print("-" * 70)

print(f"X_train shape : {X_train.shape}")
print(f"y_train shape : {y_train.shape}")


print("\nTesting Data")
print("-" * 70)

print(f"X_test shape  : {X_test.shape}")
print(f"y_test shape  : {y_test.shape}")

======================================================================
TRAIN-TEST SPLIT
======================================================================
Training Data
----------------------------------------------------------------------
X_train shape : (183579, 21)
y_train shape : (183579,)

Testing Data
----------------------------------------------------------------------
X_test shape  : (45895, 21)
y_test shape  : (45895,)

In [6]:
# =============================================================================
# CLASS DISTRIBUTION AFTER SPLIT
# =============================================================================


print("=" * 70)
print("TRAINING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_train.value_counts(normalize=True)*100)
    .round(2)
)



print("\n" + "=" * 70)
print("TESTING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_test.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TRAINING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

======================================================================
TESTING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [7]:
# =============================================================================
# STEP 4: FEATURE SCALING
# =============================================================================


from sklearn.preprocessing import StandardScaler


print("=" * 70)
print("FEATURE SCALING USING STANDARD SCALER")
print("=" * 70)


# Initialize scaler
scaler = StandardScaler()


# Fit only on training data
X_train_scaled = scaler.fit_transform(X_train)


# Transform test data using same scaler
X_test_scaled = scaler.transform(X_test)



print("Scaling completed successfully")


print("\n" + "=" * 70)
print("SHAPE AFTER SCALING")
print("=" * 70)


print(f"X_train_scaled shape : {X_train_scaled.shape}")
print(f"X_test_scaled shape  : {X_test_scaled.shape}")

======================================================================
FEATURE SCALING USING STANDARD SCALER
======================================================================
Scaling completed successfully

======================================================================
SHAPE AFTER SCALING
======================================================================
X_train_scaled shape : (183579, 21)
X_test_scaled shape  : (45895, 21)

In [8]:
# =============================================================================
# CONVERT SCALED DATA BACK TO DATAFRAME
# =============================================================================


X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
)


X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns
)



print("=" * 70)
print("SCALED TRAIN DATA PREVIEW")
print("=" * 70)


display(X_train_scaled.head())

======================================================================
SCALED TRAIN DATA PREVIEW
======================================================================

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.096408,-0.889095,0.205176,-0.395435,1.072035,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,-4.187359,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,1.13290,-0.350440,0.020709,0.529942
1,1.096408,1.124739,0.205176,0.786628,-0.932805,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,0.238814,-0.3204,0.375330,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,-0.986375,-1.381726
2,-0.912069,1.124739,0.205176,-0.690951,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,1.027793,1.007859
3,-0.912069,1.124739,0.205176,-0.986467,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,1.591006,0.020709,-0.425892
4,1.096408,-0.889095,0.205176,0.195596,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,1.314239,-0.455262,0.698722,2.095428,-0.88269,-0.350440,-0.986375,-0.425892

In [9]:
# =============================================================================
# SCALING VERIFICATION
# =============================================================================


print("=" * 70)
print("MEAN AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.mean().round(2)
)



print("\n" + "=" * 70)
print("STANDARD DEVIATION AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.std().round(2)
)

======================================================================
MEAN AFTER SCALING
======================================================================

HighBP                  0.0
HighChol                0.0
CholCheck              -0.0
BMI                    -0.0
Smoker                 -0.0
Stroke                  0.0
HeartDiseaseorAttack    0.0
PhysActivity           -0.0
Fruits                 -0.0
Veggies                -0.0
HvyAlcoholConsump      -0.0
AnyHealthcare           0.0
NoDocbcCost             0.0
GenHlth                 0.0
MentHlth                0.0
PhysHlth                0.0
DiffWalk               -0.0
Sex                    -0.0
Age                     0.0
Education              -0.0
Income                 -0.0
dtype: float64

======================================================================
STANDARD DEVIATION AFTER SCALING
======================================================================

HighBP                  1.0
HighChol                1.0
CholCheck               1.0
BMI                     1.0
Smoker                  1.0
Stroke                  1.0
HeartDiseaseorAttack    1.0
PhysActivity            1.0
Fruits                  1.0
Veggies                 1.0
HvyAlcoholConsump       1.0
AnyHealthcare           1.0
NoDocbcCost             1.0
GenHlth                 1.0
MentHlth                1.0
PhysHlth                1.0
DiffWalk                1.0
Sex                     1.0
Age                     1.0
Education               1.0
Income                  1.0
dtype: float64

# BORUTA

## 1. Baseline

In [10]:
!pip install boruta

Collecting boruta
  Downloading Boruta-0.4.3-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: numpy>=1.10.4 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from boruta) (2.1.3)
Requirement already satisfied: scikit-learn>=0.17.1 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from boruta) (1.6.1)
Requirement already satisfied: scipy>=0.17.0 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from boruta) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from scikit-learn>=0.17.1->boruta) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from scikit-learn>=0.17.1->boruta) (3.5.0)
Downloading Boruta-0.4.3-py3-none-any.whl (57 kB)
Installing collected packages: boruta
Successfully installed boruta-0.4.3

In [12]:
# =============================================================================
# BORUTA BASELINE FEATURE SELECTION (TOP-K = 5,10,15,20)
# =============================================================================

from boruta import BorutaPy
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np


# =============================================================================
# BORUTA FEATURE SELECTION
# =============================================================================

# Random Forest used internally by Boruta
rf_boruta = RandomForestClassifier(
    n_estimators=200,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)


# Initialize Boruta
boruta_selector = BorutaPy(
    estimator=rf_boruta,

    n_estimators="auto",

    verbose=0,

    random_state=42,

    max_iter=100,

    perc=100
)


# -------------------------------------------------------------------------
# Fit Boruta ONLY on training data
# -------------------------------------------------------------------------

boruta_selector.fit(
    X_train_scaled.values,
    y_train.values
)


# =============================================================================
# CREATE BORUTA RANKING
# =============================================================================

boruta_scores = pd.DataFrame({

    "Feature": X_train_scaled.columns,

    "Boruta Rank": boruta_selector.ranking_,

    "Confirmed": boruta_selector.support_,

    "Tentative": boruta_selector.support_weak_

})


# -------------------------------------------------------------------------
# Sort by Boruta rank
# -------------------------------------------------------------------------

boruta_scores = boruta_scores.sort_values(
    by=["Boruta Rank", "Feature"]
).reset_index(drop=True)


print("=" * 70)
print("BORUTA FEATURE RANKING")
print("=" * 70)

print(boruta_scores)


# =============================================================================
# TOP-K FEATURE SELECTION
# =============================================================================

k_values = [5, 10, 15, 20]

boruta_results = {}


for k in k_values:

    # ---------------------------------------------------------------------
    # Select top-k features according to Boruta ranking
    # ---------------------------------------------------------------------

    top_features = (
        boruta_scores
        .head(k)["Feature"]
        .tolist()
    )


    # ---------------------------------------------------------------------
    # Boolean mask for selecting columns
    # ---------------------------------------------------------------------

    mask = X_train_scaled.columns.isin(
        top_features
    )


    # ---------------------------------------------------------------------
    # Select training and testing features
    # ---------------------------------------------------------------------

    X_train_selected = X_train_scaled.loc[
        :, mask
    ]

    X_test_selected = X_test_scaled.loc[
        :, mask
    ]


    # ---------------------------------------------------------------------
    # Store results
    # ---------------------------------------------------------------------

    boruta_results[k] = {

        "features": top_features,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "scores": boruta_scores.head(k)

    }


    # ---------------------------------------------------------------------
    # Display
    # ---------------------------------------------------------------------

    print("=" * 70)
    print(f"TOP {k} BORUTA FEATURES")
    print("=" * 70)

    print(top_features)

    print("\nBoruta Ranking:")
    print(
        boruta_scores.head(k)
    )

======================================================================
BORUTA FEATURE RANKING
======================================================================
                 Feature  Boruta Rank  Confirmed  Tentative
0                    Age            1       True      False
1                    BMI            1       True      False
2                GenHlth            1       True      False
3                 HighBP            2      False      False
4                 Income            3      False      False
5               PhysHlth            4      False      False
6               HighChol            5      False      False
7              Education            6      False      False
8               MentHlth            7      False      False
9               DiffWalk            8      False      False
10  HeartDiseaseorAttack            9      False      False
11                   Sex           10      False      False
12                Smoker           11      False      False
13                Fruits           12      False      False
14          PhysActivity           13      False      False
15               Veggies           14      False      False
16     HvyAlcoholConsump           15      False      False
17           NoDocbcCost           16      False      False
18                Stroke           17      False      False
19             CholCheck           18      False      False
20         AnyHealthcare           19      False      False
======================================================================
TOP 5 BORUTA FEATURES
======================================================================
['Age', 'BMI', 'GenHlth', 'HighBP', 'Income']

Boruta Ranking:
   Feature  Boruta Rank  Confirmed  Tentative
0      Age            1       True      False
1      BMI            1       True      False
2  GenHlth            1       True      False
3   HighBP            2      False      False
4   Income            3      False      False
======================================================================
TOP 10 BORUTA FEATURES
======================================================================
['Age', 'BMI', 'GenHlth', 'HighBP', 'Income', 'PhysHlth', 'HighChol', 'Education', 'MentHlth', 'DiffWalk']

Boruta Ranking:
     Feature  Boruta Rank  Confirmed  Tentative
0        Age            1       True      False
1        BMI            1       True      False
2    GenHlth            1       True      False
3     HighBP            2      False      False
4     Income            3      False      False
5   PhysHlth            4      False      False
6   HighChol            5      False      False
7  Education            6      False      False
8   MentHlth            7      False      False
9   DiffWalk            8      False      False
======================================================================
TOP 15 BORUTA FEATURES
======================================================================
['Age', 'BMI', 'GenHlth', 'HighBP', 'Income', 'PhysHlth', 'HighChol', 'Education', 'MentHlth', 'DiffWalk', 'HeartDiseaseorAttack', 'Sex', 'Smoker', 'Fruits', 'PhysActivity']

Boruta Ranking:
                 Feature  Boruta Rank  Confirmed  Tentative
0                    Age            1       True      False
1                    BMI            1       True      False
2                GenHlth            1       True      False
3                 HighBP            2      False      False
4                 Income            3      False      False
5               PhysHlth            4      False      False
6               HighChol            5      False      False
7              Education            6      False      False
8               MentHlth            7      False      False
9               DiffWalk            8      False      False
10  HeartDiseaseorAttack            9      False      False
11                   Sex           10      False      False
12                Smoker           11      False      False
13                Fruits           12      False      False
14          PhysActivity           13      False      False
======================================================================
TOP 20 BORUTA FEATURES
======================================================================
['Age', 'BMI', 'GenHlth', 'HighBP', 'Income', 'PhysHlth', 'HighChol', 'Education', 'MentHlth', 'DiffWalk', 'HeartDiseaseorAttack', 'Sex', 'Smoker', 'Fruits', 'PhysActivity', 'Veggies', 'HvyAlcoholConsump', 'NoDocbcCost', 'Stroke', 'CholCheck']

Boruta Ranking:
                 Feature  Boruta Rank  Confirmed  Tentative
0                    Age            1       True      False
1                    BMI            1       True      False
2                GenHlth            1       True      False
3                 HighBP            2      False      False
4                 Income            3      False      False
5               PhysHlth            4      False      False
6               HighChol            5      False      False
7              Education            6      False      False
8               MentHlth            7      False      False
9               DiffWalk            8      False      False
10  HeartDiseaseorAttack            9      False      False
11                   Sex           10      False      False
12                Smoker           11      False      False
13                Fruits           12      False      False
14          PhysActivity           13      False      False
15               Veggies           14      False      False
16     HvyAlcoholConsump           15      False      False
17           NoDocbcCost           16      False      False
18                Stroke           17      False      False
19             CholCheck           18      False      False

In [13]:
# =============================================================================
# BASELINE MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        random_state=42,

        eval_metric="logloss",
        scale_pos_weight=(y_train == 0).sum() / (y_train == 1).sum()
    )
}

In [14]:
# =============================================================================
# MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


results = []


for k in k_values:

    Xtr = boruta_results[k]["X_train"]

    Xts = boruta_results[k]["X_test"]

    features = ", ".join(
        boruta_results[k]["features"]
    )


    # ---------------------------------------------------------------------
    # Evaluate every model
    # ---------------------------------------------------------------------

    for model_name, model in models.items():

        # Fit model
        model.fit(
            Xtr,
            y_train
        )


        # Predictions
        y_pred = model.predict(
            Xts
        )


        # Probability predictions
        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        # Store metrics
        results.append({

            "Method": "Boruta",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )

        })


# =============================================================================
# FINAL BORUTA RESULTS TABLE
# =============================================================================

boruta_results_df = pd.DataFrame(
    results
)


display(
    boruta_results_df
)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Boruta,5,Logistic Regression,"Age, BMI, GenHlth, HighBP, Income",0.704347,0.308659,0.752671,0.437787,0.797671
1,Boruta,5,Random Forest,"Age, BMI, GenHlth, HighBP, Income",0.723172,0.300155,0.608349,0.401977,0.736248
2,Boruta,5,XGBoost,"Age, BMI, GenHlth, HighBP, Income",0.695784,0.304544,0.770623,0.436562,0.800745
3,Boruta,10,Logistic Regression,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.709533,0.313077,0.753099,0.442288,0.804871
4,Boruta,10,Random Forest,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.812136,0.340370,0.243482,0.283887,0.740769
5,Boruta,10,XGBoost,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.706765,0.313157,0.768770,0.445031,0.805572
6,Boruta,15,Logistic Regression,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.713150,0.316450,0.754808,0.445941,0.807144
7,Boruta,15,Random Forest,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.837063,0.410317,0.149594,0.219252,0.767797
8,Boruta,15,XGBoost,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.710056,0.315947,0.768913,0.447865,0.808701
9,Boruta,20,Logistic Regression,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.714195,0.318100,0.759652,0.448425,0.810549
10,Boruta,20,Random Forest,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.842358,0.453247,0.149167,0.224461,0.776700
11,Boruta,20,XGBoost,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.712627,0.318123,0.768770,0.450023,0.811615

In [15]:
boruta_results_df.to_csv(
    "../../../results/diabetes/baseline/boruta_baseline_results.csv",
    index=False
)

## 2. DODA

In [16]:
import sys
import subprocess

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "--upgrade",
    "--force-reinstall",
    "--no-cache-dir",
    "git+https://github.com/anandha-3679/DODA.git"
])

0

In [17]:
import sys
import doda
from doda import DODASelector
import inspect

print("Python:", sys.executable)
print("DODA:", doda.__file__)
print("Selector:", inspect.getfile(DODASelector))

Python: c:\Users\Anandha Lakshmi\Downloads\Anaconda\python.exe
DODA: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\__init__.py
Selector: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\selector.py

In [18]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

from doda import DODASelector

from doda.adapters import SklearnAdapter

from doda.knowledge.providers import JSONProvider

from doda.fusion import HadamardFusion

In [20]:
# =============================================================================
# BORUTA + DODA FEATURE SELECTION
# =============================================================================

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from boruta import BorutaPy


# -------------------------------------------------------------------------
# Top-K values
# -------------------------------------------------------------------------

k_values = [5, 10, 15, 20]


# -------------------------------------------------------------------------
# Clinical knowledge provider
# -------------------------------------------------------------------------

provider = JSONProvider(
    "clinical_weights.json"
)


# -------------------------------------------------------------------------
# Fusion method
# -------------------------------------------------------------------------

fusion = HadamardFusion()


# -------------------------------------------------------------------------
# Store DODA results
# -------------------------------------------------------------------------

doda_results = {}


# =============================================================================
# RUN BORUTA + DODA FOR EACH TOP-K
# =============================================================================

for k in k_values:

    print("\n" + "=" * 70)
    print(f"BORUTA + DODA — TOP {k} FEATURES")
    print("=" * 70)


    # ---------------------------------------------------------------------
    # Random Forest estimator used by Boruta
    # ---------------------------------------------------------------------

    rf_boruta = RandomForestClassifier(
        n_estimators=200,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    )


    # ---------------------------------------------------------------------
    # Boruta operator
    # ---------------------------------------------------------------------

    boruta = BorutaPy(
        estimator=rf_boruta,
        n_estimators="auto",
        max_iter=100,
        perc=100,
        random_state=42,
        verbose=0
    )


    # ---------------------------------------------------------------------
    # Wrap Boruta as a DODA operator
    # ---------------------------------------------------------------------

    boruta_operator = SklearnAdapter(
        boruta
    )


    # ---------------------------------------------------------------------
    # DODA selector
    # ---------------------------------------------------------------------

    selector = DODASelector(
        operators=[boruta_operator],
        provider=provider,
        fusion=fusion,
        top_k=k
    )


    # ---------------------------------------------------------------------
    # Fit DODA on TRAINING data
    # ---------------------------------------------------------------------

    X_train_selected = selector.fit_transform(
        X_train_scaled,
        y_train
    )


    # ---------------------------------------------------------------------
    # Transform TEST data
    # ---------------------------------------------------------------------

    X_test_selected = selector.transform(
        X_test_scaled
    )


    # ---------------------------------------------------------------------
    # Selected features
    # ---------------------------------------------------------------------

    selected_features = selector.get_selected_features()


    print("\nSelected Features:")
    print(selected_features)


    # ---------------------------------------------------------------------
    # Store everything needed for later evaluation
    # ---------------------------------------------------------------------

    doda_results[k] = {

        "selector": selector,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "features": selected_features,

        "raw_math_scores": selector.raw_math_scores_,

        "math_scores": selector.math_scores_,

        "clinical_weights": selector.clinical_weights_,

        "final_scores": selector.final_scores_
    }


print("\n" + "=" * 70)
print("BORUTA + DODA FEATURE SELECTION COMPLETED")
print("=" * 70)

======================================================================
BORUTA + DODA — TOP 5 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000014F0B1F5810>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.18000000000000002), 'CholCheck': np.float64(0.022222222222222223), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.05454545454545454), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.03076923076923077), 'Fruits': np.float64(0.016666666666666666), 'Veggies': np.float64(0.014285714285714285), 'HvyAlcoholConsump': np.float64(0.013333333333333334), 'AnyHealthcare': np.float64(0.010526315789473684), 'NoDocbcCost': np.float64(0.0125), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.07142857142857142), 'PhysHlth': np.float64(0.2), 'DiffWalk': np.float64(0.1125), 'Sex': np.float64(0.020000000000000004), 'Age': np.float64(0.9), 'Education': np.float64(0.049999999999999996), 'Income': np.float64(0.09999999999999999)}
Top 5 Features Selected: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth']

Selected Features:
['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth']

======================================================================
BORUTA + DODA — TOP 10 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000014F0B1F5810>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.18000000000000002), 'CholCheck': np.float64(0.022222222222222223), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.05454545454545454), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.03076923076923077), 'Fruits': np.float64(0.016666666666666666), 'Veggies': np.float64(0.014285714285714285), 'HvyAlcoholConsump': np.float64(0.013333333333333334), 'AnyHealthcare': np.float64(0.010526315789473684), 'NoDocbcCost': np.float64(0.0125), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.07142857142857142), 'PhysHlth': np.float64(0.2), 'DiffWalk': np.float64(0.1125), 'Sex': np.float64(0.020000000000000004), 'Age': np.float64(0.9), 'Education': np.float64(0.049999999999999996), 'Income': np.float64(0.09999999999999999)}
Top 10 Features Selected: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Income', 'MentHlth']

Selected Features:
['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Income', 'MentHlth']

======================================================================
BORUTA + DODA — TOP 15 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000014F0B1F5810>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.18000000000000002), 'CholCheck': np.float64(0.022222222222222223), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.05454545454545454), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.03076923076923077), 'Fruits': np.float64(0.016666666666666666), 'Veggies': np.float64(0.014285714285714285), 'HvyAlcoholConsump': np.float64(0.013333333333333334), 'AnyHealthcare': np.float64(0.010526315789473684), 'NoDocbcCost': np.float64(0.0125), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.07142857142857142), 'PhysHlth': np.float64(0.2), 'DiffWalk': np.float64(0.1125), 'Sex': np.float64(0.020000000000000004), 'Age': np.float64(0.9), 'Education': np.float64(0.049999999999999996), 'Income': np.float64(0.09999999999999999)}
Top 15 Features Selected: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Income', 'MentHlth', 'Stroke', 'Smoker', 'Education', 'PhysActivity', 'CholCheck']

Selected Features:
['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Income', 'MentHlth', 'Stroke', 'Smoker', 'Education', 'PhysActivity', 'CholCheck']

======================================================================
BORUTA + DODA — TOP 20 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000014F0B1F5810>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.18000000000000002), 'CholCheck': np.float64(0.022222222222222223), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.05454545454545454), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.03076923076923077), 'Fruits': np.float64(0.016666666666666666), 'Veggies': np.float64(0.014285714285714285), 'HvyAlcoholConsump': np.float64(0.013333333333333334), 'AnyHealthcare': np.float64(0.010526315789473684), 'NoDocbcCost': np.float64(0.0125), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.07142857142857142), 'PhysHlth': np.float64(0.2), 'DiffWalk': np.float64(0.1125), 'Sex': np.float64(0.020000000000000004), 'Age': np.float64(0.9), 'Education': np.float64(0.049999999999999996), 'Income': np.float64(0.09999999999999999)}
Top 20 Features Selected: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Income', 'MentHlth', 'Stroke', 'Smoker', 'Education', 'PhysActivity', 'CholCheck', 'Sex', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'NoDocbcCost']

Selected Features:
['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Income', 'MentHlth', 'Stroke', 'Smoker', 'Education', 'PhysActivity', 'CholCheck', 'Sex', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'NoDocbcCost']

======================================================================
BORUTA + DODA FEATURE SELECTION COMPLETED
======================================================================

In [21]:
# CELL 2
# =============================================================================
# INSPECT MATHEMATICAL SCORES
# =============================================================================

k = 10

selector = doda_results[k]["selector"]

# -----------------------------------------------------------------------------
# Raw mathematical scores
# -----------------------------------------------------------------------------

raw_math_scores = pd.DataFrame(
    selector.raw_math_scores_.items(),
    columns=[
        "Feature",
        "Raw Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Normalized mathematical scores
# -----------------------------------------------------------------------------

normalized_math_scores = pd.DataFrame(
    selector.math_scores_.items(),
    columns=[
        "Feature",
        "Normalized Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Combine both
# -----------------------------------------------------------------------------

math_scores = raw_math_scores.merge(
    normalized_math_scores,
    on="Feature"
)

math_scores = math_scores.sort_values(
    by="Normalized Math Score",
    ascending=False
)

print("=" * 70)
print("MATHEMATICAL SCORES")
print("=" * 70)

display(math_scores)

======================================================================
MATHEMATICAL SCORES
======================================================================

                 Feature  Raw Math Score  Normalized Math Score
3                    BMI        1.000000               1.000000
13               GenHlth        1.000000               1.000000
18                   Age        1.000000               1.000000
0                 HighBP        0.500000               0.500000
20                Income        0.333333               0.333333
15              PhysHlth        0.250000               0.250000
1               HighChol        0.200000               0.200000
19             Education        0.166667               0.166667
14              MentHlth        0.142857               0.142857
16              DiffWalk        0.125000               0.125000
6   HeartDiseaseorAttack        0.111111               0.111111
17                   Sex        0.100000               0.100000
4                 Smoker        0.090909               0.090909
8                 Fruits        0.083333               0.083333
7           PhysActivity        0.076923               0.076923
9                Veggies        0.071429               0.071429
10     HvyAlcoholConsump        0.066667               0.066667
12           NoDocbcCost        0.062500               0.062500
5                 Stroke        0.058824               0.058824
2              CholCheck        0.055556               0.055556
11         AnyHealthcare        0.052632               0.052632